"""Conservative transport limits for public HTTP boundaries."""

MAX_REQUEST_BODY_BYTES = 256 * 1024
MAX_INPUT_TEXT_CHARS = 12_000
MAX_MESSAGE_TEXT_CHARS = 12_000
MAX_TRANSCRIPT_MESSAGES = 128
MAX_CONTENT_PARTS = 32
MAX_GENERATION_HISTORY_MESSAGES = 8
MAX_GENERATION_HISTORY_CHARS = 8_000
